version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./replit/frontend.replit.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    env_file:
      - .env.replit
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./replit/backend.replit.Dockerfile
    environment:
      - PORT=5000
      - DATABASE_URL= postgresql://postgres.jmimavnryovxveyxqxco:YjlT6avR059pSHv4@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - STRIPE_SECRET_KEY=test123
    volumes:
      - ./:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "5000:80"  # Map port 5000 to nginx for browser access
    volumes:
      - ./replit/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
