[deployment]
deploymentTarget = "autoscale"
build = ["vite", "build", "&&", "node", "build.mjs"]
run = ["node", "start.js"]

[deployment.env]
NODE_ENV = "production"
PORT = "5000"

[deployment.publicDir]
path = "dist/public"