[deployment]
deploymentTarget = "autoscale"
build = ["node", "deploy-build.js"]
run = ["node", "production-server.js"]

[deployment.env]
NODE_ENV = "production"
PORT = "5000"

[deployment.publicDir]
path = "dist/public"