[deployment]
deploymentTarget = "autoscale"
build = ["sh", "-c", "vite build && node build.mjs"]
run = ["node", "app.js"]

[deployment.env]
NODE_ENV = "production"

[deployment.publicDir]
path = "dist/public"