[deployment]
deploymentTarget = "autoscale"
build = ["npm", "run", "build"]
run = ["node", "production-server.js"]

[deployment.env]
NODE_ENV = "production"
PORT = "80"

[deployment.publicDir]
path = "dist/public"