[deployment]
deploymentTarget = "autoscale"
build = ["sh", "-c", "vite build && node build-production.mjs"]
run = ["node", "start-production.js"]

[deployment.env]
NODE_ENV = "production"
PORT = "5000"

[deployment.publicDir]
path = "dist/public"