[deployment]
deploymentTarget = "autoscale"
build = ["vite", "build", "&&", "node", "build-production.mjs"]
run = ["node", "production-server.js"]

[deployment.env]
NODE_ENV = "production"
PORT = "80"

[deployment.publicDir]
path = "dist/public"