[deployment]
deploymentTarget = "autoscale"
build = ["npm", "run", "build"]
run = ["node", "start.js"]

[deployment.env]
NODE_ENV = "production"
PORT = "5000"

[deployment.publicDir]
path = "dist/public"