

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "drizzle";


ALTER SCHEMA "drizzle" OWNER TO "postgres";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."cleanup_old_analytics"() RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  DELETE FROM analytics_events WHERE created_at < CURRENT_DATE - INTERVAL '30 days';
END;
$$;


ALTER FUNCTION "public"."cleanup_old_analytics"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Meditations" (
    "id" bigint NOT NULL,
    "name" "text",
    "link" "text",
    "section_title" "text",
    "subtitle" "text"
);


ALTER TABLE "public"."Meditations" OWNER TO "postgres";


ALTER TABLE "public"."Meditations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Meditations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."acts" (
    "id" integer NOT NULL,
    "user_id" "text",
    "category" "text" NOT NULL,
    "subtype" "text",
    "amount" integer DEFAULT 0,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "payment_intent_id" "text"
);


ALTER TABLE "public"."acts" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."acts_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."acts_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."acts_id_seq" OWNED BY "public"."acts"."id";



CREATE TABLE IF NOT EXISTS "public"."after_brochas_prayers" (
    "id" integer NOT NULL,
    "prayer_name" "text" NOT NULL,
    "hebrew_text" "text" NOT NULL,
    "english_translation" "text" NOT NULL,
    "description" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."after_brochas_prayers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."after_brochas_prayers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."after_brochas_prayers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."after_brochas_prayers_id_seq" OWNED BY "public"."after_brochas_prayers"."id";



CREATE TABLE IF NOT EXISTS "public"."analytics_events" (
    "id" integer NOT NULL,
    "event_type" "text" NOT NULL,
    "event_data" "jsonb",
    "session_id" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."analytics_events" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."analytics_events_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."analytics_events_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."analytics_events_id_seq" OWNED BY "public"."analytics_events"."id";



CREATE TABLE IF NOT EXISTS "public"."birkat_hamazon_prayers" (
    "id" integer NOT NULL,
    "prayer_type" "text" NOT NULL,
    "hebrew_text" "text" NOT NULL,
    "english_translation" "text" NOT NULL,
    "order_index" integer DEFAULT 0
);


ALTER TABLE "public"."birkat_hamazon_prayers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."birkat_hamazon_prayers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."birkat_hamazon_prayers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."birkat_hamazon_prayers_id_seq" OWNED BY "public"."birkat_hamazon_prayers"."id";



CREATE TABLE IF NOT EXISTS "public"."brochas" (
    "id" bigint NOT NULL,
    "Title" "text",
    "Hebrew Text" "text",
    "English Text" "text",
    "special_occasions" boolean,
    "description" "text",
    "order_index" integer
);


ALTER TABLE "public"."brochas" OWNER TO "postgres";


ALTER TABLE "public"."brochas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."brochas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."campaigns" (
    "id" integer NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "goal_amount" integer NOT NULL,
    "current_amount" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."campaigns" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."campaigns_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."campaigns_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."campaigns_id_seq" OWNED BY "public"."campaigns"."id";



CREATE TABLE IF NOT EXISTS "public"."community_impact" (
    "id" integer NOT NULL,
    "from_date" "date" NOT NULL,
    "until_date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "image_url" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."community_impact" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."community_impact_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."community_impact_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."community_impact_id_seq" OWNED BY "public"."community_impact"."id";



CREATE TABLE IF NOT EXISTS "public"."daily_chizuk" (
    "id" integer NOT NULL,
    "date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "content" "text",
    "audio_url" "text" NOT NULL,
    "speaker" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "provider" "text",
    "speaker_website" "text"
);


ALTER TABLE "public"."daily_chizuk" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."daily_chizuk_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."daily_chizuk_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."daily_chizuk_id_seq" OWNED BY "public"."daily_chizuk"."id";



CREATE TABLE IF NOT EXISTS "public"."daily_emuna" (
    "id" integer NOT NULL,
    "date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "content" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "audio_url" "text" NOT NULL,
    "speaker" "text",
    "provider" "text",
    "speaker_website" "text"
);


ALTER TABLE "public"."daily_emuna" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."daily_halacha" (
    "id" integer NOT NULL,
    "date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "provider" "text",
    "footnotes" "text"
);


ALTER TABLE "public"."daily_halacha" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."daily_halacha_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."daily_halacha_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."daily_halacha_id_seq" OWNED BY "public"."daily_halacha"."id";



CREATE SEQUENCE IF NOT EXISTS "public"."daily_mussar_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."daily_mussar_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."daily_mussar_id_seq" OWNED BY "public"."daily_emuna"."id";



CREATE TABLE IF NOT EXISTS "public"."daily_recipes" (
    "id" integer NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "ingredients" "text" NOT NULL,
    "instructions" "text" NOT NULL,
    "servings" "text",
    "prep_time" "text",
    "cook_time" "text",
    "difficulty" "text",
    "image_url" "text",
    "tags" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "date" "date" NOT NULL,
    "thank_you_message" "text"
);


ALTER TABLE "public"."daily_recipes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."daily_stats" (
    "id" integer NOT NULL,
    "date" "date" NOT NULL,
    "unique_users" integer DEFAULT 0,
    "page_views" integer DEFAULT 0,
    "tehillim_completed" integer DEFAULT 0,
    "names_processed" integer DEFAULT 0,
    "modal_completions" "jsonb" DEFAULT '{}'::"jsonb",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "books_completed" integer DEFAULT 0,
    "total_acts" integer DEFAULT 0,
    "tzedaka_acts" integer DEFAULT 0,
    "money_raised" integer DEFAULT 0,
    "active_campaign_total" integer DEFAULT 0,
    "put_a_coin_total" integer DEFAULT 0,
    "sponsor_a_day_total" integer DEFAULT 0,
    "gave_elsewhere_count" integer DEFAULT 0
);


ALTER TABLE "public"."daily_stats" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."daily_stats_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."daily_stats_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."daily_stats_id_seq" OWNED BY "public"."daily_stats"."id";



CREATE TABLE IF NOT EXISTS "public"."discount_promotions" (
    "id" integer NOT NULL,
    "title" "text" NOT NULL,
    "subtitle" "text",
    "logo_url" "text",
    "link_url" "text",
    "start_date" timestamp without time zone NOT NULL,
    "end_date" timestamp without time zone NOT NULL,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "target_location" "text" DEFAULT 'worldwide'::"text" NOT NULL
);


ALTER TABLE "public"."discount_promotions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."discount_promotions_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."discount_promotions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."discount_promotions_id_seq" OWNED BY "public"."discount_promotions"."id";



CREATE TABLE IF NOT EXISTS "public"."donations" (
    "id" integer NOT NULL,
    "stripe_payment_intent_id" "text",
    "amount" integer NOT NULL,
    "donation_type" "text" DEFAULT 'General Donation'::"text" NOT NULL,
    "sponsor_name" "text",
    "dedication" "text",
    "email" "text",
    "status" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "fundraise_up_id" character varying(255),
    "supporter_id" character varying(255),
    "currency" character varying(10) DEFAULT 'USD'::character varying,
    "recurring" boolean DEFAULT false,
    "livemode" boolean DEFAULT true,
    "campaign" "text",
    "raw_data" "jsonb",
    "user_id" "text",
    "type" "text",
    "in_honor_of" "text",
    "message" "text",
    "campaign_id" "text",
    "stripe_session_id" "text",
    "metadata" "jsonb"
);


ALTER TABLE "public"."donations" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."donations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."donations_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."donations_id_seq" OWNED BY "public"."donations"."id";



CREATE TABLE IF NOT EXISTS "public"."featured_content" (
    "id" integer NOT NULL,
    "date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "provider" "text",
    "footnotes" "text"
);


ALTER TABLE "public"."featured_content" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."global_tehillim_progress" (
    "id" integer NOT NULL,
    "current_perek" integer DEFAULT 1 NOT NULL,
    "last_updated" timestamp without time zone DEFAULT "now"(),
    "completed_by" "text",
    "current_name_id" integer
);


ALTER TABLE "public"."global_tehillim_progress" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."global_tehillim_progress_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."global_tehillim_progress_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."global_tehillim_progress_id_seq" OWNED BY "public"."global_tehillim_progress"."id";



CREATE SEQUENCE IF NOT EXISTS "public"."loshon_horah_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."loshon_horah_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."loshon_horah_id_seq" OWNED BY "public"."featured_content"."id";



CREATE TABLE IF NOT EXISTS "public"."maariv_prayers" (
    "id" integer NOT NULL,
    "prayer_type" "text" NOT NULL,
    "hebrew_text" "text" NOT NULL,
    "english_translation" "text" NOT NULL,
    "order_index" integer DEFAULT 0
);


ALTER TABLE "public"."maariv_prayers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."maariv_prayers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."maariv_prayers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."maariv_prayers_id_seq" OWNED BY "public"."maariv_prayers"."id";



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" integer NOT NULL,
    "date" "date" NOT NULL,
    "title" character varying(255) NOT NULL,
    "message" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."messages_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."messages_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."messages_id_seq" OWNED BY "public"."messages"."id";



CREATE TABLE IF NOT EXISTS "public"."mincha_prayers" (
    "id" integer NOT NULL,
    "prayer_type" "text" NOT NULL,
    "hebrew_text" "text" NOT NULL,
    "english_translation" "text" NOT NULL,
    "order_index" integer DEFAULT 0
);


ALTER TABLE "public"."mincha_prayers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."mincha_prayers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."mincha_prayers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."mincha_prayers_id_seq" OWNED BY "public"."mincha_prayers"."id";



CREATE TABLE IF NOT EXISTS "public"."morning_prayers" (
    "id" integer NOT NULL,
    "prayer_type" "text" NOT NULL,
    "hebrew_text" "text" NOT NULL,
    "english_translation" "text" NOT NULL,
    "order_index" integer DEFAULT 0
);


ALTER TABLE "public"."morning_prayers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."morning_prayers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."morning_prayers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."morning_prayers_id_seq" OWNED BY "public"."morning_prayers"."id";



CREATE TABLE IF NOT EXISTS "public"."nishmas_text" (
    "id" integer NOT NULL,
    "language" "text" NOT NULL,
    "full_text" "text" NOT NULL,
    "source" "text" DEFAULT 'Nishmas.net'::"text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."nishmas_text" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."nishmas_text_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."nishmas_text_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."nishmas_text_id_seq" OWNED BY "public"."nishmas_text"."id";



CREATE TABLE IF NOT EXISTS "public"."parsha_vorts" (
    "id" integer NOT NULL,
    "from_date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "content" "text",
    "audio_url" "text" NOT NULL,
    "speaker" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "speaker_website" "text",
    "until_date" "date" DEFAULT '2025-07-20'::"date" NOT NULL,
    "thank_you_message" "text"
);


ALTER TABLE "public"."parsha_vorts" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."parsha_vorts_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."parsha_vorts_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."parsha_vorts_id_seq" OWNED BY "public"."parsha_vorts"."id";



CREATE TABLE IF NOT EXISTS "public"."pirkei_avot" (
    "id" integer NOT NULL,
    "chapter" integer NOT NULL,
    "perek" integer NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "order_index" integer NOT NULL
);


ALTER TABLE "public"."pirkei_avot" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."pirkei_avot_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."pirkei_avot_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."pirkei_avot_id_seq" OWNED BY "public"."pirkei_avot"."id";



CREATE TABLE IF NOT EXISTS "public"."pirkei_avot_progress" (
    "id" integer NOT NULL,
    "last_updated" timestamp without time zone DEFAULT "now"(),
    "current_order_index" integer DEFAULT 1 NOT NULL
);


ALTER TABLE "public"."pirkei_avot_progress" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."pirkei_avot_progress_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."pirkei_avot_progress_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."pirkei_avot_progress_id_seq" OWNED BY "public"."pirkei_avot_progress"."id";



CREATE TABLE IF NOT EXISTS "public"."push_notifications" (
    "id" integer NOT NULL,
    "title" "text" NOT NULL,
    "body" "text" NOT NULL,
    "icon" "text",
    "badge" "text",
    "url" "text",
    "data" "jsonb",
    "sent_at" timestamp without time zone DEFAULT "now"(),
    "sent_count" integer DEFAULT 0,
    "success_count" integer DEFAULT 0,
    "failure_count" integer DEFAULT 0,
    "created_by" "text"
);


ALTER TABLE "public"."push_notifications" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."push_notifications_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."push_notifications_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."push_notifications_id_seq" OWNED BY "public"."push_notifications"."id";



CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" integer NOT NULL,
    "endpoint" "text" NOT NULL,
    "p256dh" "text" NOT NULL,
    "auth" "text" NOT NULL,
    "session_id" "text",
    "subscribed" boolean DEFAULT true,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."push_subscriptions_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."push_subscriptions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."push_subscriptions_id_seq" OWNED BY "public"."push_subscriptions"."id";



CREATE SEQUENCE IF NOT EXISTS "public"."shabbat_recipes_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."shabbat_recipes_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."shabbat_recipes_id_seq" OWNED BY "public"."daily_recipes"."id";



CREATE TABLE IF NOT EXISTS "public"."shop_items" (
    "id" integer NOT NULL,
    "store_name" "text" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "coupon_code" "text",
    "background_image_url" "text" NOT NULL,
    "external_url" "text",
    "is_active" boolean DEFAULT true
);


ALTER TABLE "public"."shop_items" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."shop_items_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."shop_items_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."shop_items_id_seq" OWNED BY "public"."shop_items"."id";



CREATE TABLE IF NOT EXISTS "public"."sponsors" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "hebrew_name" "text",
    "sponsorship_date" "text" NOT NULL,
    "message" "text",
    "is_active" boolean DEFAULT true,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "in_honor_memory_of" "text"
);


ALTER TABLE "public"."sponsors" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."sponsors_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."sponsors_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."sponsors_id_seq" OWNED BY "public"."sponsors"."id";



CREATE TABLE IF NOT EXISTS "public"."table_inspirations" (
    "id" integer NOT NULL,
    "from_date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "media_url_1" "text",
    "media_type_1" "text",
    "media_url_2" "text",
    "media_type_2" "text",
    "media_url_3" "text",
    "media_type_3" "text",
    "media_url_4" "text",
    "media_type_4" "text",
    "media_url_5" "text",
    "media_type_5" "text",
    "until_date" "date" DEFAULT '2025-07-20'::"date" NOT NULL
);


ALTER TABLE "public"."table_inspirations" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."table_inspirations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."table_inspirations_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."table_inspirations_id_seq" OWNED BY "public"."table_inspirations"."id";



CREATE TABLE IF NOT EXISTS "public"."tehillim" (
    "id" integer NOT NULL,
    "english_number" integer NOT NULL,
    "hebrew_number" "text" NOT NULL,
    "english_text" "text" NOT NULL,
    "hebrew_text" "text" NOT NULL,
    "part_number" integer
);


ALTER TABLE "public"."tehillim" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."tehillim_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."tehillim_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."tehillim_id_seq" OWNED BY "public"."tehillim"."id";



CREATE TABLE IF NOT EXISTS "public"."tehillim_names" (
    "id" integer NOT NULL,
    "hebrew_name" "text" NOT NULL,
    "reason" "text" NOT NULL,
    "reason_english" "text",
    "date_added" timestamp without time zone DEFAULT "now"(),
    "expires_at" timestamp without time zone,
    "user_id" integer
);


ALTER TABLE "public"."tehillim_names" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."tehillim_names_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."tehillim_names_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."tehillim_names_id_seq" OWNED BY "public"."tehillim_names"."id";



CREATE TABLE IF NOT EXISTS "public"."womens_prayers" (
    "id" integer NOT NULL,
    "category" "text" NOT NULL,
    "prayer_name" "text" NOT NULL,
    "hebrew_text" "text",
    "english_translation" "text",
    "description" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."womens_prayers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."womens_prayers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."womens_prayers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."womens_prayers_id_seq" OWNED BY "public"."womens_prayers"."id";



ALTER TABLE ONLY "public"."acts" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."acts_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."after_brochas_prayers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."after_brochas_prayers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."analytics_events" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."analytics_events_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."birkat_hamazon_prayers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."birkat_hamazon_prayers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."campaigns" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."campaigns_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."community_impact" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."community_impact_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."daily_chizuk" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."daily_chizuk_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."daily_emuna" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."daily_mussar_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."daily_halacha" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."daily_halacha_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."daily_recipes" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."shabbat_recipes_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."daily_stats" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."daily_stats_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."discount_promotions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."discount_promotions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."donations" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."donations_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."featured_content" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."loshon_horah_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."global_tehillim_progress" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."global_tehillim_progress_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."maariv_prayers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."maariv_prayers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."messages" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."messages_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."mincha_prayers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."mincha_prayers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."morning_prayers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."morning_prayers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."nishmas_text" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."nishmas_text_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."parsha_vorts" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."parsha_vorts_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."pirkei_avot" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."pirkei_avot_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."pirkei_avot_progress" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."pirkei_avot_progress_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."push_notifications" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."push_notifications_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."push_subscriptions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."push_subscriptions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."shop_items" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."shop_items_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."sponsors" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."sponsors_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."table_inspirations" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."table_inspirations_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."tehillim" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tehillim_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."tehillim_names" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tehillim_names_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."womens_prayers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."womens_prayers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."Meditations"
    ADD CONSTRAINT "Meditations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."acts"
    ADD CONSTRAINT "acts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."after_brochas_prayers"
    ADD CONSTRAINT "after_brochas_prayers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."analytics_events"
    ADD CONSTRAINT "analytics_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."birkat_hamazon_prayers"
    ADD CONSTRAINT "birkat_hamazon_prayers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."brochas"
    ADD CONSTRAINT "brochas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."campaigns"
    ADD CONSTRAINT "campaigns_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."community_impact"
    ADD CONSTRAINT "community_impact_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_chizuk"
    ADD CONSTRAINT "daily_chizuk_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_halacha"
    ADD CONSTRAINT "daily_halacha_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_emuna"
    ADD CONSTRAINT "daily_mussar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_stats"
    ADD CONSTRAINT "daily_stats_date_key" UNIQUE ("date");



ALTER TABLE ONLY "public"."daily_stats"
    ADD CONSTRAINT "daily_stats_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."discount_promotions"
    ADD CONSTRAINT "discount_promotions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."donations"
    ADD CONSTRAINT "donations_fundraise_up_id_key" UNIQUE ("fundraise_up_id");



ALTER TABLE ONLY "public"."donations"
    ADD CONSTRAINT "donations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."donations"
    ADD CONSTRAINT "donations_stripe_payment_intent_id_key" UNIQUE ("stripe_payment_intent_id");



ALTER TABLE ONLY "public"."global_tehillim_progress"
    ADD CONSTRAINT "global_tehillim_progress_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."featured_content"
    ADD CONSTRAINT "loshon_horah_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."maariv_prayers"
    ADD CONSTRAINT "maariv_prayers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_date_key" UNIQUE ("date");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."mincha_prayers"
    ADD CONSTRAINT "mincha_prayers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."morning_prayers"
    ADD CONSTRAINT "morning_prayers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."nishmas_text"
    ADD CONSTRAINT "nishmas_text_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."parsha_vorts"
    ADD CONSTRAINT "parsha_vorts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pirkei_avot"
    ADD CONSTRAINT "pirkei_avot_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pirkei_avot_progress"
    ADD CONSTRAINT "pirkei_avot_progress_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."push_notifications"
    ADD CONSTRAINT "push_notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_endpoint_key" UNIQUE ("endpoint");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_recipes"
    ADD CONSTRAINT "shabbat_recipes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."shop_items"
    ADD CONSTRAINT "shop_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sponsors"
    ADD CONSTRAINT "sponsors_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."table_inspirations"
    ADD CONSTRAINT "table_inspirations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tehillim_names"
    ADD CONSTRAINT "tehillim_names_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tehillim"
    ADD CONSTRAINT "tehillim_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."womens_prayers"
    ADD CONSTRAINT "womens_prayers_pkey" PRIMARY KEY ("id");



CREATE INDEX "analytics_events_created_idx" ON "public"."analytics_events" USING "btree" ("created_at");



CREATE INDEX "analytics_events_type_idx" ON "public"."analytics_events" USING "btree" ("event_type");



CREATE INDEX "idx_analytics_session_id" ON "public"."analytics_events" USING "btree" ("session_id");



CREATE INDEX "idx_sponsors_date_active" ON "public"."sponsors" USING "btree" ("sponsorship_date", "is_active");



CREATE INDEX "idx_sponsors_is_active" ON "public"."sponsors" USING "btree" ("is_active");



CREATE INDEX "idx_sponsors_sponsorship_date" ON "public"."sponsors" USING "btree" ("sponsorship_date");



CREATE INDEX "idx_tehillim_names_expires_at" ON "public"."tehillim_names" USING "btree" ("expires_at");



CREATE INDEX "pirkei_avot_order_idx" ON "public"."pirkei_avot" USING "btree" ("order_index");



ALTER TABLE "public"."Meditations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."brochas" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."after_brochas_prayers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."birkat_hamazon_prayers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."brochas";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."campaigns";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."daily_chizuk";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."daily_emuna";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."daily_halacha";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."daily_recipes";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."discount_promotions";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."featured_content";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."global_tehillim_progress";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."messages";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."mincha_prayers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."morning_prayers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."nishmas_text";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."parsha_vorts";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."pirkei_avot";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."pirkei_avot_progress";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."shop_items";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."sponsors";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."table_inspirations";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."tehillim_names";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."womens_prayers";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."cleanup_old_analytics"() TO "anon";
GRANT ALL ON FUNCTION "public"."cleanup_old_analytics"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."cleanup_old_analytics"() TO "service_role";


















GRANT ALL ON TABLE "public"."Meditations" TO "anon";
GRANT ALL ON TABLE "public"."Meditations" TO "authenticated";
GRANT ALL ON TABLE "public"."Meditations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Meditations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Meditations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Meditations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."acts" TO "anon";
GRANT ALL ON TABLE "public"."acts" TO "authenticated";
GRANT ALL ON TABLE "public"."acts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."acts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."acts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."acts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."after_brochas_prayers" TO "anon";
GRANT ALL ON TABLE "public"."after_brochas_prayers" TO "authenticated";
GRANT ALL ON TABLE "public"."after_brochas_prayers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."after_brochas_prayers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."after_brochas_prayers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."after_brochas_prayers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."analytics_events" TO "anon";
GRANT ALL ON TABLE "public"."analytics_events" TO "authenticated";
GRANT ALL ON TABLE "public"."analytics_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."analytics_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."analytics_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."analytics_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."birkat_hamazon_prayers" TO "anon";
GRANT ALL ON TABLE "public"."birkat_hamazon_prayers" TO "authenticated";
GRANT ALL ON TABLE "public"."birkat_hamazon_prayers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."birkat_hamazon_prayers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."birkat_hamazon_prayers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."birkat_hamazon_prayers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."brochas" TO "anon";
GRANT ALL ON TABLE "public"."brochas" TO "authenticated";
GRANT ALL ON TABLE "public"."brochas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."brochas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."brochas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."brochas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."campaigns" TO "anon";
GRANT ALL ON TABLE "public"."campaigns" TO "authenticated";
GRANT ALL ON TABLE "public"."campaigns" TO "service_role";



GRANT ALL ON SEQUENCE "public"."campaigns_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."campaigns_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."campaigns_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."community_impact" TO "anon";
GRANT ALL ON TABLE "public"."community_impact" TO "authenticated";
GRANT ALL ON TABLE "public"."community_impact" TO "service_role";



GRANT ALL ON SEQUENCE "public"."community_impact_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."community_impact_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."community_impact_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."daily_chizuk" TO "anon";
GRANT ALL ON TABLE "public"."daily_chizuk" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_chizuk" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_chizuk_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_chizuk_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_chizuk_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."daily_emuna" TO "anon";
GRANT ALL ON TABLE "public"."daily_emuna" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_emuna" TO "service_role";



GRANT ALL ON TABLE "public"."daily_halacha" TO "anon";
GRANT ALL ON TABLE "public"."daily_halacha" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_halacha" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_halacha_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_halacha_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_halacha_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_mussar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_mussar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_mussar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."daily_recipes" TO "anon";
GRANT ALL ON TABLE "public"."daily_recipes" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_recipes" TO "service_role";



GRANT ALL ON TABLE "public"."daily_stats" TO "anon";
GRANT ALL ON TABLE "public"."daily_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_stats" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_stats_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_stats_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_stats_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."discount_promotions" TO "anon";
GRANT ALL ON TABLE "public"."discount_promotions" TO "authenticated";
GRANT ALL ON TABLE "public"."discount_promotions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."discount_promotions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."discount_promotions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."discount_promotions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."donations" TO "anon";
GRANT ALL ON TABLE "public"."donations" TO "authenticated";
GRANT ALL ON TABLE "public"."donations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."donations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."donations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."donations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."featured_content" TO "anon";
GRANT ALL ON TABLE "public"."featured_content" TO "authenticated";
GRANT ALL ON TABLE "public"."featured_content" TO "service_role";



GRANT ALL ON TABLE "public"."global_tehillim_progress" TO "anon";
GRANT ALL ON TABLE "public"."global_tehillim_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."global_tehillim_progress" TO "service_role";



GRANT ALL ON SEQUENCE "public"."global_tehillim_progress_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."global_tehillim_progress_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."global_tehillim_progress_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."loshon_horah_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."loshon_horah_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."loshon_horah_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."maariv_prayers" TO "anon";
GRANT ALL ON TABLE "public"."maariv_prayers" TO "authenticated";
GRANT ALL ON TABLE "public"."maariv_prayers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."maariv_prayers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."maariv_prayers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."maariv_prayers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."mincha_prayers" TO "anon";
GRANT ALL ON TABLE "public"."mincha_prayers" TO "authenticated";
GRANT ALL ON TABLE "public"."mincha_prayers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."mincha_prayers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."mincha_prayers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."mincha_prayers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."morning_prayers" TO "anon";
GRANT ALL ON TABLE "public"."morning_prayers" TO "authenticated";
GRANT ALL ON TABLE "public"."morning_prayers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."morning_prayers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."morning_prayers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."morning_prayers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."nishmas_text" TO "anon";
GRANT ALL ON TABLE "public"."nishmas_text" TO "authenticated";
GRANT ALL ON TABLE "public"."nishmas_text" TO "service_role";



GRANT ALL ON SEQUENCE "public"."nishmas_text_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."nishmas_text_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."nishmas_text_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."parsha_vorts" TO "anon";
GRANT ALL ON TABLE "public"."parsha_vorts" TO "authenticated";
GRANT ALL ON TABLE "public"."parsha_vorts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."parsha_vorts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."parsha_vorts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."parsha_vorts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pirkei_avot" TO "anon";
GRANT ALL ON TABLE "public"."pirkei_avot" TO "authenticated";
GRANT ALL ON TABLE "public"."pirkei_avot" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pirkei_avot_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pirkei_avot_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pirkei_avot_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pirkei_avot_progress" TO "anon";
GRANT ALL ON TABLE "public"."pirkei_avot_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."pirkei_avot_progress" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pirkei_avot_progress_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pirkei_avot_progress_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pirkei_avot_progress_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."push_notifications" TO "anon";
GRANT ALL ON TABLE "public"."push_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."push_notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."push_notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."push_notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."push_notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."push_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."shabbat_recipes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."shabbat_recipes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."shabbat_recipes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."shop_items" TO "anon";
GRANT ALL ON TABLE "public"."shop_items" TO "authenticated";
GRANT ALL ON TABLE "public"."shop_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."shop_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."shop_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."shop_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sponsors" TO "anon";
GRANT ALL ON TABLE "public"."sponsors" TO "authenticated";
GRANT ALL ON TABLE "public"."sponsors" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sponsors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sponsors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sponsors_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."table_inspirations" TO "anon";
GRANT ALL ON TABLE "public"."table_inspirations" TO "authenticated";
GRANT ALL ON TABLE "public"."table_inspirations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."table_inspirations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."table_inspirations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."table_inspirations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tehillim" TO "anon";
GRANT ALL ON TABLE "public"."tehillim" TO "authenticated";
GRANT ALL ON TABLE "public"."tehillim" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tehillim_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tehillim_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tehillim_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tehillim_names" TO "anon";
GRANT ALL ON TABLE "public"."tehillim_names" TO "authenticated";
GRANT ALL ON TABLE "public"."tehillim_names" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tehillim_names_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tehillim_names_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tehillim_names_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."womens_prayers" TO "anon";
GRANT ALL ON TABLE "public"."womens_prayers" TO "authenticated";
GRANT ALL ON TABLE "public"."womens_prayers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."womens_prayers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."womens_prayers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."womens_prayers_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;

