name: Deploy fronted to s3
on:
  push:
    branches:
      - staging
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'  # or whatever version you're using
    - name: 'Set Environment Variables'
      id: set-environment
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "VITE_MODE=production" >> $GITHUB_ENV
          echo "S3_BUCKET=ezras-nashim-frontend-production" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=E1D5U1KTDNFYHS" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" = "staging" ]; then
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "VITE_MODE=staging" >> $GITHUB_ENV
          echo "S3_BUCKET=ezras-nashim-frontend" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=E4DFY6W9PG5RQ" >> $GITHUB_ENV

        fi

    - name: Build and deploy
      run: |
        npm install
        npx vite build --mode ${{ env.VITE_MODE }}

    - name: Configure AWS Credentials Action for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        role-to-assume: arn:aws:iam::551437426075:role/GitHub-OIDC-Policy
        aws-region: "eu-central-1"
    - name: Deploy to S3
      run: |
        aws s3 sync dist/public s3://${S3_BUCKET}/
        aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
          --paths "/*"
